name: regun
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flame: ^1.18.0
  flame_audio: ^2.10.2
  flame_riverpod: ^5.4.2
  flutter_riverpod: ^2.5.1
  phosphor_flutter: ^2.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "app_icon/launcher.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#000000"
  image: "app_icon/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
          weight: 400

    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Orbitron-Bold.ttf
          weight: 700
        - asset: assets/fonts/Orbitron-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Orbitron-Medium.ttf
          weight: 500
        - asset: assets/fonts/Orbitron-Regular.ttf
          weight: 400
